name: dev_flutter_cursos_getx_restapi_sqlite_sqflite
description: "Project flutter. http,Getx,Sqlite,UniTest"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  http: ^1.2.1
  shimmer: ^3.0.0
  sqflite: ^2.0.0+3
  cached_network_image: ^3.1.0
  



  # cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

